version: "3.7"

services:
  grafana:
    build:
      context: .
      args:
        grafana_version: ${GRAFANA_VERSION:-main}
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,grafana-clock-panel
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    ports:
      - 3001:3000/tcp
    volumes:
      - ../../plugins/redshift-datasource/dist:/var/lib/grafana/plugins/basic-datasource
      - ./provisioning:/etc/grafana/provisioning
